# Generated by Django 3.2 on 2021-05-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymobApp', '0002_auto_20210501_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
    ]
