# Generated by Django 3.2 on 2021-05-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymobApp', '0003_rename_user_id_product_user'),
        ('paymobApp', '0004_insert_groups'),
    ]

    operations = [
    ]
