# Generated by Django 3.2 on 2021-05-01 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymobApp', '0005_merge_20210501_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='createdBy',
        ),
        migrations.AddField(
            model_name='product',
            name='purchasedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='auth.user'),
            preserve_default=False,
        ),
    ]
